---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - TV
 - Podcasts
 - 'App Store'
 - News
 - Contacts
 - Reminders

dockitems_persist:
 - name: "Launchpad"
   path: "/System/Applications/Launchpad.app"
   pos: 1
 - name: "Music"
   path: "/System/Applications/Music.app"
   pos: 2
 - name: "Chrome"
   path: "/Applications/Google\ Chrome.app"
   pos: 3
 - name: "Mail"
   path: "/System/Applications/Mail.app/"
   pos: 4
 - name: "Visual Studio Code"
   path: "/Applications/Visual Studio Code.app/"
   pos: 5
 - name: "Sublime Text"
   path: "/Applications/Sublime Text.app/"
   pos: 6
 - name: "Slack"
   path: "/Applications/Slack.app/"
   pos: 7
 - name: "Messages"
   path: "/System/Applications/Messages.app"
   pos: 8
 - name: "Calendar"
   path: "/System/Applications/Calendar.app"
   pos: 9
 - name: "1Password"
   path: "/Applications/1Password.app/"
   pos: 10
 - name: "iTerm"
   path: "/Applications/iTerm.app/"
   pos: 11

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/andrewglass3/dotfiles.git
dotfiles_repo_accept_hostkey: true
become: True
changed_when: False
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - awscli
  - ack
  - bash-completion
  - curl
  - checkov
  - git
  - gh
  - go
  - gpg
  - iperf
  - jinja2-cli
  - jq
  - kubectl
  - kubectx
  - neofetch
  - netcat
  - nmap
  - npm
  - openssl
  - powerlevel10k
  - readline
  - ssh-copy-id
  - wget
  - zsh-history-substring-search
  - zsh
  # - zsh-autosuggestions
  # - zsh-completions

homebrew_taps:
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - chromedriver
  - docker
  - discord
  - fig
  - firefox
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - font-meslo-for-powerline
  - google-chrome
  - iterm2
  - kubecontext
  - microsoft-auto-update
  - microsoft-office
  - microsoft-teams
  - monitorcontrol
  - notion
  - podman-desktop
  - rectangle
  - spotify
  - sequel-ace
  - slack
  - sublime-text
  - transmit
  - visual-studio-code
  - viscosity
  - surfshark
  - whatsapp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1503446680, name: "PastePal" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1153157709, name: "Speedtest by Ookla" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: ibm/plex
# state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"
  - "LSP-terraform"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
